### ISSUE TITLE
Enter key refreshes browser

### ISSUE THREAD

**Issue by nvwieren** [mendix/SearchInput#1]
After the last update using the enter key refreshes the browser instead of triggering the microflow..

**Comment by RoelandSalij** [comment]
Thanks, I noticed it too. I quickly updated the contents of v1.1 but you beat me to it!
Can you verify that it works correctly if you download it again?

**Comment by nvwieren** [comment]
Hi, it's still happening; I already had the latest version it seems.

**Comment by JelteMX** [comment]
[Version 1.1.1](https://github.com/mendix/SearchInput/releases/tag/v1.1.1) should have fixed this problem. We also use this widget as the search box in the AppStore (top-right). Can you tell us what the settings are? Also: which Mendix version do you use and what browser?

**Comment by Rvthof** [comment]
This issue still exists in Firefox, it seems.

**Comment by JelteMX** [comment]
@nvwieren: Can you check [this version](https://github.com/mendix/SearchInput/blob/master/test/widgets/SearchInput.mpk?raw=true) and see if this fixes your problem?

**Comment by nvwieren** [comment]
@JelteMX @Rvthof issue seems to be resolved now, also in Firefox(mac) for me. Thanks!

**Comment by RoelandSalij** [comment]
Thanks for your feedback. I've published the 1.2 version to the Mendix App Store.
