### ISSUE TITLE
Closing a popup with searchinput widget gives error in mx7.0.2

### ISSUE THREAD

**Issue by melvingrootenboers** [mendix/SearchInput#10]
Mx 7.0.2

1. Add Searchinput widget to popup page
2. Open popup
3. Close popup

Error: SearchInput_widget_SearchInput_0.applyContext: Error: SearchInput_widget_SearchInput_0.applyContext: TypeError: Cannot read property 'unsubscribe' of undefined

**Comment by JelteMX** [comment]
Problem is in [Line 184](https://github.com/mendix/SearchInput/blob/master/src/SearchInput/widget/SearchInput.js#L184), it's referring to the context within that function, instead of the widget. I'll fix this.

**Comment by JelteMX** [comment]
Fixed and published in [1.5.0](https://github.com/mendix/SearchInput/releases/tag/v1.5.0), updated in AppStore
