### ISSUE TITLE
Error count badge on tabcontainer is not removed

### ISSUE THREAD

**Issue by khode-mx** [mendix/SearchInput#11]
Somehow the executeMicroflow function does not result in proper handling of the validation badge count at the tabcontainer level. 

Normally having a validation error would result in an increase of the notification badge, which also happens in with this widget and is correct behaviour. However, as soon as you correct the error, in the next validation run the notification badge count is not decreased.

To correct this, I've added the following quick fix to my instance of the widget, but would like to know what the proper way would be to have this fixed (which is why I haven't created a pull request yet).

In the executeMicroflow function I simply added:
` if(this._hadValidationFeedback) {
                    this._decreaseValidationNotification();
                    this._hadValidationFeedback = false;
                }`

near the end of the function.

**Comment by JelteMX** [comment]
I decided to add this to ``_clearValidations``, your solution is right. Thanks for reporting! I'll add this to the new version of the widget

**Comment by JelteMX** [comment]
Fixed and published in [1.5.0](https://github.com/mendix/SearchInput/releases/tag/v1.5.0), updated in AppStore
