### ISSUE TITLE
IE11 problem and 3 wishes

### ISSUE THREAD

**Issue by jandelange** [mendix/SearchInput#2]
Great Widget, very handy in a grid layout. Some issues:
Wish 1: option to choose another image, because you do more then only search
Wish 2: possibility to give it a label
Wish 3: Tooltip
Error: Gives error under IE11 No constructor found for widget ( chrome no problem and in IE11 cleared history and cash but still the error )

for info: Jan@jadela.nl

**Comment by JelteMX** [comment]
What is the Mendix version you are using? We have tested this in MX 5.18.0 and MX 6.3.1, using Chrome, Firefox and IE11. No issues found.

**Comment by JelteMX** [comment]
Closing issue due to no response. Wish 1 is [granted](https://github.com/mendix/SearchInput/commit/1be3511019ebcaa22df50b61e9a37dae6fdca4c8), the other two need to be submitted as feature requests separately.
