### ISSUE TITLE
Javascript error when using Validation Feedback action

### ISSUE THREAD

**Issue by dan-covaliu** [mendix/SearchInput#3]
In my scenario, I want to display an error message if the user searches with less than 2 characters. In the Microflow I check the input length and use a Validation Feedback to display the message related to the search field. The widget disappears from the page an a JavaScript error is logged to the console (in IE11 and Chrome) : `SearchInput_widget_SearchInput_0.executeMicroFlow: XAS error executing microflow`

**Comment by JelteMX** [comment]
Can you tell us how you have structured this? If we run the Show validation test in the test-project, we don't see a similar error

**Comment by dan-covaliu** [comment]
[SearchInputIssue.zip](https://github.com/mendix/SearchInput/files/289723/SearchInputIssue.zip)

here is an example: run it, click open page; input 2 chars in the searchfield then press enter. the search field disappears; check browser console.
Thanks!

**Comment by JelteMX** [comment]
Thanks for the test-project, I created a fix. Can you test [this one](https://github.com/mendix/SearchInput/raw/master/test/widgets/SearchInput.mpk) for me? 

The Javascript error remains, but that's plain logic. The validation is shown now and will disappear when you type again. Let me know if this fixes your problem, then I'll create a new version in the AppStore

**Comment by dan-covaliu** [comment]
Yes it works!
Thank you so much!

**Comment by JelteMX** [comment]
Fix included in [v1.3.2](https://github.com/mendix/SearchInput/releases/tag/v1.3.2) and updated in the AppStore. Thanks for reporting and the straight to the point test-project to reproduce the issue :-) 👍
