### ISSUE TITLE
Input not passed to entity attribute if search is not pressed.

### ISSUE THREAD

**Issue by khode-mx** [mendix/SearchInput#5]
Hi, the following situation occurs in our project:

User types text in the searchbox (attribute A), but decides not to hit the enter key, preventing the search microflow from running. On another field (attribute B), we have an On Change microflow which is triggered after input was changed (again, on attribute B).

What happens is that in the On Change triggered by attribute B, the value for attribute A is empty. 

Am I doing something wrong, as this does not seem correct?

Running Mx 6.5.1 with the latest Appstore release (v1.3.2)

**Comment by RoelandSalij** [comment]
Does the Microflow(triggered by the On change) refresh the object?
What probably happens is that the input gets an update from the client, resetting the value in the widget.

In the code the value of the attribute is only set 'on enter'. We can add the onchange event here, and set the value of the contextobject.

**Comment by khode-mx** [comment]
Yes, the On Change does perform a refresh of the object. Could you implement the change in behaviour so that the value is also set whenever a user doesn't 'on enter'? Would help us out a lot!

**Comment by RoelandSalij** [comment]
Yes! Thanks for the feedback.
