### ISSUE TITLE
Validation error not passed to tabcontainer badge

### ISSUE THREAD

**Issue by khode-mx** [mendix/SearchInput#6]
I've noticed that if you have the widget in a tabcontainer (or multiple instances), and a Show validation message is triggered, these validation errors are not added to the tabcontainer level which displays the number of validation errors in a badge.

So instead of showing a badge with the number 3, right now the value 1 is displayed if I have three fields, of which 2 are the SearchInput widget.

**Comment by RoelandSalij** [comment]
@JelteMX, can you review this please?
@dkho87, can you test if the widget in the test project of this repository fixes your issue?

**Comment by khode-mx** [comment]
Seems to be working fine now, many thanks!
